description: [Community Maintained Image of ArkOS for the K36 Console and Similar Clones]
github:
  mega_url: https://mega.nz/folder/Vlxz0aRD#VdoTDuBSDUoN1JTpcEujPQ
show_downloads: false
theme: jekyll-theme-slate
